export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const GET_USER = 'GET_USER';
export const SET_ACTIVE_SECTION = 'SET_ACTIVE_SECTION';
export const GET_INVENTORY = 'GET_INVENTORY';
export const SET_INVENTORY = 'SET_INVENTORY';

